server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://host.docker.internal:3100/loki/api/v1/push

scrape_configs:
  - job_name: system_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: systemlogs
          __path__: /var/log/*log


  # - job_name: nginx_logs
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: nginx
  #         __path__: /var/log/nginx-promtail/*.log
